### ISSUE TITLE
Make master compatible with both OpenCV 2 and 3

### ISSUE THREAD

**Issue by goncalopp** [goncalopp/simple-ocr-opencv#20]
If possible, we should merge the opencv3 branch back into master in a way that makes it work for both versions. CI needs to be configured to test both.

@RedFantom 's comment:

>Edit: using cv2.__version__, it is possible to retrieve a version number in str format, but the python-opencv package from the Ubuntu repositories provides $Rev 4227 as version number instead of 3.x.x or 2.x.x, so that complicates things.

I'm getting '2.4.9.1' on Debian stable (Jessie), so this might Ubuntu-specific. It's annoying, but I guess we can hardcode specific values for the Ubuntu versions we know for now.

**Comment by RedFantom** [comment]
Well, the one in the Ubuntu repositories is OpenCV 2, so instead of checking for OpenCV 2, we should check for OpenCV 3. I have changed this behaviour in my commits to [`versions`](https://github.com/RedFantom/simple-ocr-opencv/tree/versions)-branch on my fork of the repository. It's ready for merging after #18.

**Comment by goncalopp** [comment]
>Well, the one in the Ubuntu repositories is OpenCV 2, so instead of checking for OpenCV 2, we should check for OpenCV 3. I have changed this behaviour in my commits to versions-branch on my fork of the repository. It's ready for merging after #18.

True, it's cv 2.4 even for Ubuntu 16.10. I've merged #18, feel free to rebase and submit a PR

**Comment by RedFantom** [comment]
This issue can be closed, right? We've got OpenCV 3 support and OpenCV 2 support at the same time :) .

**Comment by goncalopp** [comment]
True - thanks!
