### ISSUE TITLE
OpenCV 3.0

### ISSUE THREAD

**Issue by dee-see** [goncalopp/simple-ocr-opencv#6]
I've just forked this repo and I'm migrating it to OpenCV 3 as I hit breaking changes. Are you interested in pull requests for an OpenCV 3 branch?

**Comment by goncalopp** [comment]
I'm not very familiar with OpenCV 3, is it going to be the default any soon? Would it be easy to maintain compatibility with both versions? If not, I think keeping a separate branch would be appropriate, and I'm happy to accept pull requests

**Comment by dee-see** [comment]
I'm completely new to the world of OpenCV and I started working with 3.0 just because it's the latest version. From what I've read they're in some sort of python 2.7 vs 3 situation where the body of work in 2.4 is too large to migrate overnight with all the breaking changes.

Alright, I'll work on my OpenCV 3 branch and send pull request once it starts feeling a little more complete! Thanks
