### ISSUE TITLE
Opencv 

### ISSUE THREAD

**Issue by sethuraman81** [goncalopp/simple-ocr-opencv#8]
Hello,

I tried to use this repository however getting an error

TypeError: only length-1 arrays can be converted to Python scalars

 self.classifier.train( features, image_file.ground.classes )
 File simple-ocr-opencv-master\classification.py", line 56, in train

i am using Python 2.7
Opencv 3.1.0 and
numpy version 1.9.1

am faily new to python and opencv, any suggestions or pointers is much appreciated.

Thanks

**Comment by goncalopp** [comment]
Hi,
This is written for OpenCV 2. heatz contributed some changes for opencv 3, can you check the opencv3 branch and let me know if it works for you?

**Comment by goncalopp** [comment]
Did this work for you?

**Comment by sethuraman81** [comment]
HI,

Yes it does work, Thanks for the message it went in to my emails-forums tab and didn't notice earlier
