### ISSUE TITLE
opencv3.0 the cv2 no this method

### ISSUE THREAD

**Issue by guoyonggang178** [goncalopp/simple-ocr-opencv#9]
File "/Users/telescopeman/project/simple-ocr-opencv/classification.py", line 47, in __init__
    self.knn= cv2.KNearest()
AttributeError: 'module' object has no attribute 'KNearest'

**Comment by goncalopp** [comment]
Did you try the opencv3 branch?

**Comment by goncalopp** [comment]
Did you get to try this?

**Comment by goncalopp** [comment]
I'm closing this, feel free to open another issue if you are still having problems

**Comment by Django-27** [comment]
in OpenCV3, please use cv2.ml.KNearest_create() instead.

**Comment by goncalopp** [comment]
@Django-27 Isn't that already done in the branch? `classification.py:46`

**Comment by Jambon1510** [comment]
Might not be the case at that time but now with a opencv 4 version, I got the issue cause condition is ==3

```
class KNNClassifier(Classifier):
    def __init__(self, k=1, debug=False):
        if get_opencv_version() == 3:
            self.knn = cv2.ml.KNearest_create()
        else:
            self.knn = cv2.KNearest()
        self.k = k
        self.debug = debug
```

**Comment by ShwetaLalwani** [comment]
How to install OpenCV 4?
